---
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options
include:
  - project: 'ipsec/citemplates'
    ref: master
    file: '/linting/superlinter.yml'

stages:
  - linting
  - test
